apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: USER
      remoteRef:
        key: app/secrets
        property: USER
    - secretKey: PASSWORD
      remoteRef:
        key: app/secrets
        property: PASSWORD
