apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-role"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
            audiences:
              - "https://centralus.oic.prod-aks.azure.com/4dfef5e0-1199-4be5-91da-2cd0b90b08da/6d8dd9aa-fd18-430c-9b9f-f3621f950429/"